version: "3.1"

services:
  db:
    container_name: mongo-gsw-sms
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
